#' @title Available metrics in scoringutils
#'
#' @return A vector with the name of all available metrics
#' @export
#' @keywords info
available_metrics <- function() {
  return(unique(c(scoringutils::metrics$Name,
                  "wis", "interval_coverage_50", "interval_coverage_90",
                  "interval_coverage_deviation")))
}


#' @title Collapse several messages to one
#'
#' @description Internal helper function to facilitate generating messages
#' and warnings.
#'
#' @param type character, should be either "messages", "warnings" or "errors"
#' @param messages the messages or warnings to collapse
#'
#' @return string with the message or warning
#' @keywords internal
collapse_messages <- function(type = "messages", messages) {
  paste0(
    "The following ",  type, " were produced when checking inputs:\n",
    paste(paste0(seq_along(messages), ". "), messages, collapse = "\n")
  )
}


#' @title Print output from `check_forecasts()`
#'
#' @description Helper function that prints the output generated by
#' `check_forecasts()`
#'
#' @param x An object of class 'scoringutils_check' as produced b y
#' `check_forecasts()`
#' @param ... additional arguments (not used here)
#'
#' @return NULL
#' @export
#' @keywords check-forecasts
#' @examples
#' check <- as_forecast(example_quantile)
#' print(check)
print.scoringutils_check <- function(x, ...) {
  cat("Your forecasts seem to be for a target of the following type:\n")
  print(x["target_type"])
  cat("and in the following format:\n")
  print(x["prediction_type"])

  cat("The unit of a single forecast is defined by:\n")
  print(x["forecast_unit"])

  cat("Cleaned data, rows with NA values in predicted or observed removed:\n")
  print.default(x["cleaned_data"])

  cat("Number of unique values per column per model:\n")
  print.default(x["unique_values"])

  colnames <- names(x)[names(x) %in% c("messages", "warnings", "errors")]
  if (length(colnames) > 0) {
    print.default(x[colnames])
  }

  return(invisible(x))
}

#' @title Filter function arguments
#'
#' @description This function compares a list of arguments with the arguments
#' that a function can accept. It only returns those arguments that can be
#' passed to the function.
#'
#' The function is used in [score()] to handle additional arguments passed to
#' [score()] that get then passed along to the different scoring functions.
#'
#' @param fun A function to which arguments shall be passed
#' @param args A list of arguments that shall be passed to fun
#'
#' @return A list of function arguments (a subset of `args`) that `fun` can
#' accept.
#' @keywords internal
filter_function_args <- function(fun, args) {
  # Check if the function accepts ... as an argument
  if ("..." %in% names(formals(fun))) {
    # If it does, return all arguments
    return(args)
  } else {
    # Identify the arguments that fun() accepts and only keep valid ones
    valid_args <- names(formals(fun))
    return(args[names(args) %in% valid_args])
  }
}


#' @title Assign attributes to an object from a named list
#' @description
#' Every list item will be made an attribute of the object.
#' @param object An object to assign attributes to
#' @param attribute_list A named list of attributes to assign to the object.
#'
#' @return The object with new attributes according to the contents of
#' `attribute_list`
#' @keywords internal
assign_attributes <- function(object, attribute_list) {
  if (is.null(object)) {
    return(NULL)
  }
  for (i in seq_along(attribute_list)) {
    setattr(object, names(attribute_list)[i], attribute_list[[i]])
  }
  return(object)
}

#' Strip attributes from an object
#' @description This function removes all attributes from an object that are
#' specified in the `attributes` argument.
#' @param object An object to remove attributes from
#' @param attributes A character vector of attribute names to remove from the
#' object
#' @return The object with attributes removed
#' @keywords internal
strip_attributes <- function(object, attributes) {
  if (is.null(object)) {
    return(NULL)
  }
  for (i in seq_along(attributes)) {
    setattr(object, attributes[i], NULL)
  }
  return(object)
}


#' @title Run a function safely
#' @description This is a wrapper function designed to run a function safely
#' when it is not completely clear what arguments could be passed to the
#' function.
#'
#' All named arguments in `...` that are not accepted by `fun` are removed.
#' All unnamed arguments are passed on to the function. In case `fun` errors,
#' the error will be converted to a warning and `run_safely` returns `NULL`.
#'
#' `run_safely` can be useful when constructing functions to be used as
#' metrics in [score()].
#'
#' @param ... Arguments to pass to `fun`
#' @param fun A function to execute
#' @return The result of `fun` or `NULL` if `fun` errors
#' @export
#' @keywords scoring
#' @examples
#' f <- function(x) {x}
#' run_safely(2, fun = f)
#' run_safely(2, y = 3, fun = f)
#' run_safely(fun = f)
#' run_safely(y = 3, fun = f)
run_safely <- function(..., fun) {
  args <- list(...)
  # Check if the function accepts ... as an argument
  if ("..." %in% names(formals(fun))) {
    valid_args <- args
  } else if (is.null(names(args))) {
    # if no arguments are named, just pass all arguments on
    valid_args <- args
  } else {
    # Identify the arguments that fun() accepts
    possible_args <- names(formals(fun))
    # keep valid arguments as well as unnamed arguments
    valid_args <- args[names(args) == "" | names(args) %in% possible_args]
  }

  result <- try(do.call(fun, valid_args), silent = TRUE)

  if (inherits(result, "try-error")) {
    msg <- conditionMessage(attr(result, "condition"))
    warning(
      "Function execution failed, returning NULL. Error: ",
      msg
    )
    return(NULL)
  }
  return(result)
}


#' Ensure That an Object is a Data Table
#' @description This function ensures that an object is a data table.
#' If the object is not a data table, it is converted to one. If the object
#' is a data table, a copy of the object is returned.
#' @param data An object to ensure is a data table
#' @return A data table
#' @keywords internal
#' @importFrom data.table copy is.data.table as.data.table
ensure_data.table <- function(data) {
  if (is.data.table(data)) {
    data <- copy(data)
  } else {
    data <- as.data.table(data)
  }
  return(data)
}

#' @title Print Information About A Forecast Object
#' @description This function prints information about a forecast object,
#' including "Forecast type", "Score columns",
#' "Forecast unit".
#' @export
#' @keywords check-forecasts
#' @examples
#' print(example_quantile %>% as_forecast)
print.forecast_binary <- function(dat, ...) {
  # Obtain forecast object information for printing
  forecast_type <- get_forecast_type(dat)
  score_cols <- get_score_names(dat)
  forecast_units <- get_forecast_unit(dat)

  # Print forecast object information
  cat("Forecast type:\n")
  print(forecast_type)

  if (!is.null(score_cols)) {
    cat("\nScore columns:\n")
    print(score_cols)
  }

  cat("\nForecast unit:\n")
  print(forecast_units)

  cat("\n")
  NextMethod(dat, ...)

  return(invisible(dat))
}

#' @rdname print.forecast_binary
#' @export
print.forecast_quantile <- print.forecast_binary

#' @rdname print.forecast_binary
#' @export
print.forecast_point <- print.forecast_binary

#' @rdname print.forecast_binary
#' @export
print.forecast_sample <- print.forecast_binary
